development:
  secret_key_base: '50423db8a60c1c0d9b4b53c2733bf9cb245bd10db9cfa9292f04436ce302565993d78aea199461d1771d0525e92df1125777c8ec342ab8f7b05052498e0ab732'
  aws_access_key_id: "not-required"
  aws_secret_access_key: "not-required"
  s3_bucket: "not-required"
  cas_url: "https://pmg-cas-staging.herokuapp.com"
  # cas_url: "http://localhost:3001"

test:
  secret_key_base: '50423db8a60c1c0d9b4b53c2733bf9cb245bd10db9cfa9292f04436ce302565993d78aea199461d1771d0525e92df1125777c8ec342ab8f7b05052498e0ab732'
  aws_access_key_id: "not-required"
  aws_secret_access_key: "not-required"
  s3_bucket: "not-required"
  cas_url: ""

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  s3_bucket: <%= ENV["S3_BUCKET"] %>
  cloud_front_url: <%= ENV["CLOUD_FRONT_URL"] %>
  bugsnag_api_key: <%= ENV["BUGSNAG_API_KEY"] %>
  cas_url: "https://pmg-cas-staging.herokuapp.com"

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  s3_bucket: <%= ENV["S3_BUCKET"] %>
  cloud_front_url: <%= ENV["CLOUD_FRONT_URL"] %>
  bugsnag_api_key: <%= ENV["BUGSNAG_API_KEY"] %>
  cas_url: "https://login.pmgdirect.net"
